import colors from '@/styles/colors'

const theme = {
  $basicFocus: colors.$N40,
  $basicHover: colors.$N20,
  $basicDefault: colors.$N30,
  $basicActive: colors.$N40,
  $basicDisabled: colors.$NA4,
  $basicFocusBorder: colors.$N40,
  $basicHoverBorder: colors.$N20,
  $basicDefaultBorder: colors.$N30,
  $basicActiveBorder: colors.$N40,
  $basicDisabledBorder: colors.$NA4,

  $basicTransparentFocus: colors.$NA16,
  $basicTransparentHover: colors.$NA8,
  $basicTransparentDefault: colors.$NA4,
  $basicTransparentActive: colors.$NA16,
  $basicTransparentDisabled: colors.$NA4,
  $basicTransparentFocusBorder: colors.$N100,
  $basicTransparentHoverBorder: colors.$N100,
  $basicTransparentDefaultBorder: colors.$N100,
  $basicTransparentActiveBorder: colors.$N100,
  $basicTransparentDisabledBorder: colors.$N40,

  $primaryFocus: colors.$P500,
  $primaryHover: colors.$P300,
  $primaryDefault: colors.$P400,
  $primaryActive: colors.$P500,
  $primaryDisabled: colors.$PA40,
  $primaryFocusBorder: colors.$P500,
  $primaryHoverBorder: colors.$P300,
  $primaryDefaultBorder: colors.$P400,
  $primaryActiveBorder: colors.$P500,
  $primaryDisabledBorder: colors.$PA40,

  $primaryTransparentFocus: colors.$PA24,
  $primaryTransparentHover: colors.$PA16,
  $primaryTransparentDefault: colors.$PA8,
  $primaryTransparentActive: colors.$PA24,
  $primaryTransparentDisabled: colors.$PA8,
  $primaryTransparentFocusBorder: colors.$P400,
  $primaryTransparentHoverBorder: colors.$P400,
  $primaryTransparentDefaultBorder: colors.$P400,
  $primaryTransparentActiveBorder: colors.$P400,
  $primaryTransparentDisabledBorder: colors.$PA24,

  $successFocus: colors.$G400,
  $successHover: colors.$G200,
  $successDefault: colors.$G300,
  $successActive: colors.$G400,
  $successDisabled: colors.$GA40,
  $successFocusBorder: colors.$G400,
  $successHoverBorder: colors.$G200,
  $successDefaultBorder: colors.$G300,
  $successActiveBorder: colors.$G400,
  $successDisabledBorder: colors.$GA40,

  $successTransparentFocus: colors.$GA24,
  $successTransparentHover: colors.$GA16,
  $successTransparentDefault: colors.$GA8,
  $successTransparentActive: colors.$GA24,
  $successTransparentDisabled: colors.$GA8,
  $successTransparentFocusBorder: colors.$G400,
  $successTransparentHoverBorder: colors.$G400,
  $successTransparentDefaultBorder: colors.$G400,
  $successTransparentActiveBorder: colors.$G400,
  $successTransparentDisabledBorder: colors.$GA16,

  $warningFocus: colors.$Y400,
  $warningHover: colors.$Y200,
  $warningDefault: colors.$Y300,
  $warningActive: colors.$Y400,
  $warningDisabled: colors.$YA40,
  $warningFocusBorder: colors.$Y400,
  $warningHoverBorder: colors.$Y200,
  $warningDefaultBorder: colors.$Y300,
  $warningActiveBorder: colors.$Y400,
  $warningDisabledBorder: colors.$YA40,

  $warningTransparentFocus: colors.$YA24,
  $warningTransparentHover: colors.$YA16,
  $warningTransparentDefault: colors.$YA8,
  $warningTransparentActive: colors.$YA24,
  $warningTransparentDisabled: colors.$YA8,
  $warningTransparentFocusBorder: colors.$Y400,
  $warningTransparentHoverBorder: colors.$Y400,
  $warningTransparentDefaultBorder: colors.$Y400,
  $warningTransparentActiveBorder: colors.$Y400,
  $warningTransparentDisabledBorder: colors.$Y200,

  $dangerFocus: colors.$R400,
  $dangerHover: colors.$R200,
  $dangerDefault: colors.$R300,
  $dangerActive: colors.$R400,
  $dangerDisabled: colors.$RA40,
  $dangerFocusBorder: colors.$R400,
  $dangerHoverBorder: colors.$R200,
  $dangerDefaultBorder: colors.$R300,
  $dangerActiveBorder: colors.$R400,
  $dangerDisabledBorder: colors.$RA40,

  $dangerTransparentFocus: colors.$RA24,
  $dangerTransparentHover: colors.$RA16,
  $dangerTransparentDefault: colors.$RA8,
  $dangerTransparentActive: colors.$RA24,
  $dangerTransparentDisabled: colors.$RA8,
  $dangerTransparentFocusBorder: colors.$R400,
  $dangerTransparentHoverBorder: colors.$R400,
  $dangerTransparentDefaultBorder: colors.$R400,
  $dangerTransparentActiveBorder: colors.$R400,
  $dangerTransparentDisabledBorder: colors.$RA16,

  $controlFocus: colors.$COLORNAME,
  $controlHover: colors.$COLORNAME,
  $controlDefault: colors.$COLORNAME,
  $controlActive: colors.$COLORNAME,
  $controlDisabled: colors.$COLORNAME,
  $controlFocusBorder: colors.$COLORNAME,
  $controlHoverBorder: colors.$COLORNAME,
  $controlDefaultBorder: colors.$COLORNAME,
  $controlActiveBorder: colors.$COLORNAME,
  $controlDisabledBorder: colors.$COLORNAME,

  $controlTransparentFocus: colors.$COLORNAME,
  $controlTransparentHover: colors.$COLORNAME,
  $controlTransparentDefault: colors.$COLORNAME,
  $controlTransparentActive: colors.$COLORNAME,
  $controlTransparentDisabled: colors.$COLORNAME,
  $controlTransparentFocusBorder: colors.$COLORNAME,
  $controlTransparentHoverBorder: colors.$COLORNAME,
  $controlTransparentDefaultBorder: colors.$COLORNAME,
  $controlTransparentActiveBorder: colors.$COLORNAME,
  $controlTransparentDisabledBorder: colors.$COLORNAME,

  $backgroundBasicLevel1: colors.$COLORNAME,
  $backgroundBasicLevel2: colors.$COLORNAME,
  $backgroundBasicLevel3: colors.$COLORNAME,
  $backgroundBasicLevel4: colors.$COLORNAME,

  $backgroundAlternativeLevel1: colors.$COLORNAME,
  $backgroundAlternativeLevel2: colors.$COLORNAME,
  $backgroundAlternativeLevel3: colors.$COLORNAME,
  $backgroundAlternativeLevel4: colors.$COLORNAME,

  $borderBasicLevel1: colors.$COLORNAME,
  $borderBasicLevel2: colors.$COLORNAME,
  $borderBasicLevel3: colors.$COLORNAME,
  $borderBasicLevel4: colors.$COLORNAME,

  $borderAlternativeLevel1: colors.$COLORNAME,
  $borderAlternativeLevel2: colors.$COLORNAME,
  $borderAlternativeLevel3: colors.$COLORNAME,
  $borderAlternativeLevel4: colors.$COLORNAME,

  $backgroundPrimaryLevel1: colors.$COLORNAME,
  $backgroundPrimaryLevel2: colors.$COLORNAME,
  $backgroundPrimaryLevel3: colors.$COLORNAME,
  $backgroundPrimaryLevel4: colors.$COLORNAME,

  $backgroundSuccessLevel1: colors.$COLORNAME,
  $backgroundSuccessLevel2: colors.$COLORNAME,
  $backgroundSuccessLevel3: colors.$COLORNAME,
  $backgroundSuccessLevel4: colors.$COLORNAME,

  $backgroundWarningLevel1: colors.$COLORNAME,
  $backgroundWarningLevel2: colors.$COLORNAME,
  $backgroundWarningLevel3: colors.$COLORNAME,
  $backgroundWarningLevel4: colors.$COLORNAME,

  $backgroundDangerLevel1: colors.$COLORNAME,
  $backgroundDangerLevel2: colors.$COLORNAME,
  $backgroundDangerLevel3: colors.$COLORNAME,
  $backgroundDangerLevel4: colors.$COLORNAME,

  $textDefault: colors.$N800,
  $textDisabled: colors.$N100,
  $textHint: colors.$N200,

  $textLight: 'white',
  $textLightDisabled: 'rgba(255, 255, 255, 0.8)',

  $textDark: colors.$N800,
  $textDarkDisabled: colors.$N100,

  $textPrimary: colors.$P500,
  $textPrimaryFocus: colors.$P500,
  $textPrimaryHover: colors.$P500,
  $textPrimaryActive: colors.$P500,
  $textPrimaryDisabled: colors.$P100,

  $textSuccess: colors.$G400,
  $textSuccessFocus: colors.$G400,
  $textSuccessHover: colors.$G400,
  $textSuccessActive: colors.$G400,
  $textSuccessDisabled: colors.$GA48,

  $textWarning: colors.$Y400,
  $textWarningFocus: colors.$Y400,
  $textWarningHover: colors.$Y400,
  $textWarningActive: colors.$Y400,
  $textWarningDisabled: colors.$YA48,

  $textDanger: colors.$R400,
  $textDangerFocus: colors.$R400,
  $textDangerHover: colors.$R400,
  $textDangerActive: colors.$R400,
  $textDangerDisabled: colors.$RA48,

  $outlineColor: colors.$COLORNAME
}

export default theme
